services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: gestion-interventions-sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=DevPassword123!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P DevPassword123! -Q 'SELECT 1'",
        ]
      interval: 30s
      timeout: 10s
      retries: 5

  adminer:
    image: adminer:latest
    container_name: gestion-interventions-adminer
    ports:
      - 8080:8080
    depends_on:
      - sqlserver

volumes:
  sqlserver_data:
